version: "3"
services:
  customer-service:
    image: nginx:alpine
    restart: always
    container_name: customer-service__nginx
    volumes:
      - ./:/app:delegated
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "8081:80"
    expose:
      - "80"
    depends_on:
      - php
      - mysqldb
    links:
      - mysqldb

  php:
    build: .
    restart: always
    container_name: customer-service__php
    volumes:
      - ./:/app:delegated
      - ./docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated
    environment:
      LOG_LEVEL: "debug"
      DEBUG: "true"

  mysqldb:
    image: mariadb:latest
    restart: always
    container_name: customer-service__mariadb
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'customer_db'
      MYSQL_USER: 'customer_user'
      MYSQL_PASSWORD: 'customer_password'

