version: "3"
services:
  customer-service:
    image: nginx:alpine
    container_name: customer-service
    volumes:
      - ./:/app:delegated
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - php

  php:
    build: .
    container_name: customer-service_php
    volumes:
      - ./:/app:delegated
      - ./docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    environment:
      LOG_LEVEL: "debug"
      DEBUG: "true"

